first commit
carlosissac/project1contactmyreps pull request #4
Opened 2020-06-11 04:13 UTC by carlosissac

first commit

2020-06-11 04:26 UTC, Wanderingtech commented on README.md
> +Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
Looks good

2020-06-11 04:27 UTC, Wanderingtech commented on index.html
> +    <title>Document</title>
i don't like this

2020-06-11 04:28 UTC, Wanderingtech requested changes
The readme is good. The boilerplate not so much

2020-06-16 00:06 UTC, closed without merging

2020-06-16 00:50 UTC, Wanderingtech reviewed
That's a lot of work. Is the responsive nature with all the devices in CSS necessary with materialize being super responsive on it's own?

2020-06-16 01:18 UTC, carlosissac commented
I just piggy backed on what I had from my weather dashboard HW.

Materialize is responsive, but there's a few elements that just don't move
the way they should do once I do the resize.

I just copy pasted from my other project and it's working fine.

Tried looking for this message in GIT but i couldn't find it.

Regards.

Issac

On Mon, Jun 15, 2020 at 5:50 PM Heather Stolz <notifications@github.com>
wrote:

> *@Wanderingtech* commented on this pull request.
>
> That's a lot of work. Is the responsive nature with all the devices in CSS
> necessary with materialize being super responsive on it's own?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/carlosissac/project1contactmyreps/pull/4#pullrequestreview-431086382>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOMDHTI7P6TVZB6PRL7O5K3RW26WPANCNFSM4N3BJLIQ>
> .
>